---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: web-app-role
    run_list:
      - recipe[capistrano-base-test::web_app_role]
    attributes:
  - name: mysql-role
    run_list:
      - recipe[capistrano-base-test::mysql_role]
    attributes:
      mysql:
        server_root_password: my-root-password
