---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: web-app-role
    run_list:
      - recipe[capistrano-base::web-app-role]
    attributes:
  - name: mysql-role
    run_list:
      - recipe[capistrano-base::mysql-role]
    attributes:
