name             'capistrano-base'
maintainer       'Adam Krone'
maintainer_email 'krone.adam@gmail.com'
license          'Apache v2.0'
description      'Installs/Configures capistrano-base'
long_description 'Installs/Configures capistrano-base'
version          '0.3.0'


depends 'apt'
depends 'users'
depends 'sudo'
depends 'ssh-hardening'
depends 'nodejs'
depends 'apache2', '~> 3.0'
depends 'database', '~> 2.3.1'
depends 'mysql', '~> 6.0'
